CREATE FUNCTION Common.CurrentEasternTime()
RETURNS DATETIME2(0)
AS
BEGIN
	RETURN CONVERT(DATETIME2(0), SWITCHOFFSET(SYSUTCDATETIME(), DATEPART(TZOFFSET, SYSUTCDATETIME() AT TIME ZONE 'Eastern Standard Time')))
END
